import { Photo } from "./types";

export const INITIAL_PHOTOS: Photo[] = [
  {
    id: "rail-001",
    title: "The Iron Giant of Cikubang Viaduct",
    description: "CC 206 locomotive leading the Executive Argo Parahyangan over the dramatic 110-meter deep Cikubang gorge. The low afternoon sun casts long metallic reflections across the steel trellis arches.",
    imageUrl: "https://images.unsplash.com/photo-1474487548417-781cb71495f3?auto=format&fit=crop&w=1800&q=85",
    thumbnailUrl: "https://images.unsplash.com/photo-1474487548417-781cb71495f3?auto=format&fit=crop&w=600&q=75",
    locomotive: "CC 206",
    trainName: "Argo Parahyangan",
    location: "Jembatan Cikubang, Padalarang",
    region: "Daop 2 Bandung",
    dateTaken: "2024-06-18T16:45:00Z",
    year: 2024,
    timeWeather: "Golden Hour",
    tags: ["CC 206", "Viaduct", "Daop 2", "Golden Hour", "Trellis Bridge", "Express"],
    cameraModel: "Sony ILCE-7M4",
    lens: "FE 24-70mm F2.8 GM II",
    focalLength: "48mm",
    aperture: "f/4.0",
    shutterSpeed: "1/1000s",
    iso: "ISO 200",
    isFeatured: true,
    aspectRatio: "landscape",
    createdAt: "2024-06-19T08:00:00Z",
  },
  {
    id: "rail-002",
    title: "Morning Mainline at Kali Progo",
    description: "Veteran CC 201 with its unmistakable nose profile traversing the iconic truss bridge over Progo River under crisp morning atmosphere, powering through early commuter traffic.",
    imageUrl: "https://images.unsplash.com/photo-1515165562839-978bbcf18277?auto=format&fit=crop&w=1800&q=85",
    thumbnailUrl: "https://images.unsplash.com/photo-1515165562839-978bbcf18277?auto=format&fit=crop&w=600&q=75",
    locomotive: "CC 201",
    trainName: "Taksaka Pagi",
    location: "Jembatan Kali Progo, Kulon Progo",
    region: "Daop 6 Yogyakarta",
    dateTaken: "2023-09-12T07:15:00Z",
    year: 2023,
    timeWeather: "Daylight",
    tags: ["CC 201", "Historic", "Daop 6", "Steel Truss", "Morning Light"],
    cameraModel: "Nikon D750",
    lens: "AF-S NIKKOR 70-200mm f/2.8E FL ED VR",
    focalLength: "135mm",
    aperture: "f/3.2",
    shutterSpeed: "1/1250s",
    iso: "ISO 160",
    isFeatured: true,
    aspectRatio: "landscape",
    createdAt: "2023-09-13T10:00:00Z",
  },
  {
    id: "rail-003",
    title: "Aerodynamic Nose on Purwosari Curve",
    description: "The streamlined aerodynamic CC 203 locomotive leaning into the sweeping superelevated curve outside Solo. Captured with high shutter speed freezing the wheelset track interaction.",
    imageUrl: "https://images.unsplash.com/photo-1508739773434-c26b3d09e071?auto=format&fit=crop&w=1800&q=85",
    thumbnailUrl: "https://images.unsplash.com/photo-1508739773434-c26b3d09e071?auto=format&fit=crop&w=600&q=75",
    locomotive: "CC 203",
    trainName: "Argo Dwipangga",
    location: "Lengkung Purwosari, Surakarta",
    region: "Daop 6 Yogyakarta",
    dateTaken: "2022-11-04T15:20:00Z",
    year: 2022,
    timeWeather: "Overcast",
    tags: ["CC 203", "Superelevation", "Daop 6", "Overcast", "High Speed"],
    cameraModel: "Canon EOS R6",
    lens: "RF 70-200mm F2.8 L IS USM",
    focalLength: "95mm",
    aperture: "f/3.5",
    shutterSpeed: "1/1600s",
    iso: "ISO 400",
    isFeatured: false,
    aspectRatio: "landscape",
    createdAt: "2022-11-05T09:30:00Z",
  },
  {
    id: "rail-004",
    title: "Twin Arches of Sakalibel at Dusk",
    description: "The monumental viaduct of Sakalibel in Bumiayu catching the last embers of sunset. General Electric CC 206 glides smoothly over the reinforced concrete arches carrying KA Sawunggalih.",
    imageUrl: "https://images.unsplash.com/photo-1520105072000-f44fc083e508?auto=format&fit=crop&w=1800&q=85",
    thumbnailUrl: "https://images.unsplash.com/photo-1520105072000-f44fc083e508?auto=format&fit=crop&w=600&q=75",
    locomotive: "CC 206",
    trainName: "KA Sawunggalih",
    location: "Jembatan Sakalibel, Bumiayu",
    region: "Daop 5 Purwokerto",
    dateTaken: "2024-08-29T17:40:00Z",
    year: 2024,
    timeWeather: "Golden Hour",
    tags: ["CC 206", "Sakalibel", "Daop 5", "Golden Hour", "Viaduct", "Signature"],
    cameraModel: "Sony ILCE-7M4",
    lens: "FE 70-200mm F2.8 GM OSS II",
    focalLength: "105mm",
    aperture: "f/4.0",
    shutterSpeed: "1/800s",
    iso: "ISO 250",
    isFeatured: true,
    aspectRatio: "landscape",
    createdAt: "2024-08-30T11:00:00Z",
  },
  {
    id: "rail-005",
    title: "Midnight Express Under the Platform Canopy",
    description: "Atmospheric long exposure at Stasiun Besar Yogyakarta. Locomotive headlights pierce the misty midnight air while travelers board the flagship Gajayana sleeping carriages.",
    imageUrl: "https://images.unsplash.com/photo-1509749837427-ac94a2553d0e?auto=format&fit=crop&w=1800&q=85",
    thumbnailUrl: "https://images.unsplash.com/photo-1509749837427-ac94a2553d0e?auto=format&fit=crop&w=600&q=75",
    locomotive: "CC 206",
    trainName: "KA Gajayana",
    location: "Stasiun Tugu, Yogyakarta",
    region: "Daop 6 Yogyakarta",
    dateTaken: "2023-12-20T23:50:00Z",
    year: 2023,
    timeWeather: "Night",
    tags: ["CC 206", "Night", "Station", "Daop 6", "Atmospheric", "Headlights"],
    cameraModel: "Sony ILCE-7M4",
    lens: "FE 50mm F1.2 GM",
    focalLength: "50mm",
    aperture: "f/1.8",
    shutterSpeed: "1/125s",
    iso: "ISO 1600",
    isFeatured: true,
    aspectRatio: "landscape",
    createdAt: "2023-12-21T02:00:00Z",
  },
  {
    id: "rail-006",
    title: "Monsoon Torrent at Terowongan Notog",
    description: "Heavy tropical rain cascading down the rock cutting near the newly dual-tracked Notog tunnel. Water sprays plume violently as a heavy freight manifest powers south.",
    imageUrl: "https://images.unsplash.com/photo-1495344517868-8ebaf0a2044a?auto=format&fit=crop&w=1800&q=85",
    thumbnailUrl: "https://images.unsplash.com/photo-1495344517868-8ebaf0a2044a?auto=format&fit=crop&w=600&q=75",
    locomotive: "CC 201",
    trainName: "KA Barang Semen",
    location: "Terowongan Notog, Banyumas",
    region: "Daop 5 Purwokerto",
    dateTaken: "2021-02-14T14:10:00Z",
    year: 2021,
    timeWeather: "Rainy",
    tags: ["CC 201", "Rainy", "Freight", "Daop 5", "Tunnel", "Monsoon"],
    cameraModel: "Nikon Z6 II",
    lens: "NIKKOR Z 24-70mm f/2.8 S",
    focalLength: "58mm",
    aperture: "f/2.8",
    shutterSpeed: "1/640s",
    iso: "ISO 800",
    isFeatured: false,
    aspectRatio: "landscape",
    createdAt: "2021-02-15T08:00:00Z",
  },
  {
    id: "rail-007",
    title: "North Coast Mainline 120 km/h Pursuit",
    description: "The flagship Argo Bromo Anggrek tearing through coastal emerald wetlands. Track ballast and overhead pantograph lines form pure geometrical perspective lines.",
    imageUrl: "https://images.unsplash.com/photo-1541427468627-a89a96e5ca1d?auto=format&fit=crop&w=1800&q=85",
    thumbnailUrl: "https://images.unsplash.com/photo-1541427468627-a89a96e5ca1d?auto=format&fit=crop&w=600&q=75",
    locomotive: "CC 206",
    trainName: "Argo Bromo Anggrek",
    location: "Lintas Pantura, Karawang - Cikampek",
    region: "Daop 1 Jakarta",
    dateTaken: "2024-05-10T16:15:00Z",
    year: 2024,
    timeWeather: "Golden Hour",
    tags: ["CC 206", "High Speed", "Pantura", "Daop 1", "Golden Hour", "Express"],
    cameraModel: "Canon EOS R5",
    lens: "RF 100-500mm F4.5-7.1 L IS USM",
    focalLength: "180mm",
    aperture: "f/5.6",
    shutterSpeed: "1/2000s",
    iso: "ISO 500",
    isFeatured: true,
    aspectRatio: "landscape",
    createdAt: "2024-05-11T12:00:00Z",
  },
  {
    id: "rail-008",
    title: "Mountain Gradients of Cirahayu Loop",
    description: "KA Lodaya navigating the challenging switchbacks and serpentine horseshoe turns of the Southern mountain spine between Tasikmalaya and Cipeundeuy.",
    imageUrl: "https://images.unsplash.com/photo-1549488344-cbb6c34cf08b?auto=format&fit=crop&w=1800&q=85",
    thumbnailUrl: "https://images.unsplash.com/photo-1549488344-cbb6c34cf08b?auto=format&fit=crop&w=600&q=75",
    locomotive: "CC 206",
    trainName: "KA Lodaya",
    location: "Petak Cirahayu - Bumi Waluya",
    region: "Daop 2 Bandung",
    dateTaken: "2020-08-19T10:30:00Z",
    year: 2020,
    timeWeather: "Daylight",
    tags: ["CC 206", "Mountains", "Daop 2", "Horseshoe Curve", "Priangan"],
    cameraModel: "Sony ILCE-7M3",
    lens: "FE 85mm F1.8",
    focalLength: "85mm",
    aperture: "f/3.5",
    shutterSpeed: "1/1000s",
    iso: "ISO 200",
    isFeatured: false,
    aspectRatio: "landscape",
    createdAt: "2020-08-20T14:00:00Z",
  },
  {
    id: "rail-009",
    title: "Heritage Steam Shunter at Rawa Pening",
    description: "Preserved vintage locomotive basking in the morning mist beside the tranquil waters of Rawa Pening lake, surrounded by towering volcanic silhouettes.",
    imageUrl: "https://images.unsplash.com/photo-1532105956626-9569c03602f6?auto=format&fit=crop&w=1800&q=85",
    thumbnailUrl: "https://images.unsplash.com/photo-1532105956626-9569c03602f6?auto=format&fit=crop&w=600&q=75",
    locomotive: "Vintage",
    trainName: "Kereta Wisata Ambarawa",
    location: "Rawa Pening, Ambarawa",
    region: "Daop 4 Semarang",
    dateTaken: "2019-07-28T06:45:00Z",
    year: 2019,
    timeWeather: "Daylight",
    tags: ["Vintage", "Heritage", "Steam", "Daop 4", "Lake", "Mountain"],
    cameraModel: "Fujifilm X-T4",
    lens: "XF 35mm F1.4 R",
    focalLength: "35mm",
    aperture: "f/2.0",
    shutterSpeed: "1/1500s",
    iso: "ISO 160",
    isFeatured: false,
    aspectRatio: "landscape",
    createdAt: "2019-07-29T07:00:00Z",
  },
];

export const GEAR_LIST = [
  {
    category: "Camera Bodies",
    items: [
      { name: "Sony Alpha 7 IV (ILCE-7M4)", role: "Primary Mainline Body", detail: "33MP Full-Frame, Real-time Eye AF, 10fps" },
      { name: "Nikon D750", role: "Long Exposure & Harsh Weather", detail: "24.3MP Full-Frame, Weather Sealed Tank" },
      { name: "Canon EOS R6", role: "High-Speed Dynamic Action", detail: "20.1MP, 20fps Electronic Shutter" },
    ],
  },
  {
    category: "Optics & Glass",
    items: [
      { name: "Sony FE 70-200mm F2.8 GM OSS II", role: "Telephoto Workhorse", detail: "Precision sharpness for curve tracking" },
      { name: "Sony FE 24-70mm F2.8 GM II", role: "Viaducts & Wide Landscapes", detail: "Corner-to-corner contrast and resolution" },
      { name: "Sony FE 135mm F1.8 GM", role: "Prime Portrait of Locomotives", detail: "Breathtaking subject isolation & dusk speed" },
      { name: "Nikon AF-S 70-200mm f/2.8E FL ED VR", role: "Reliable Trackside Companion", detail: "Unbeatable mechanical durability" },
    ],
  },
  {
    category: "Field Equipment",
    items: [
      { name: "Gitzo Mountaineer Series 3 Tripod", role: "Vibration dampening on track ballast", detail: "Carbon eXact legs" },
      { name: "Haida M10 II Filter Kit", role: "CPL + 6-Stop ND for water and sky glow", detail: "Drop-in Nano-pro coated glass" },
      { name: "Uniden Bearcat UBC125XLT", role: "Railway Radio Scanner (VHF)", detail: "Tracking train dispatch approvals" },
    ],
  },
];
